name: PlayerLocations
version: 1.1
main: dev.jayox.PlayerLocations
api-version: '1.20'
description: Get the country of the online players
commands:
  playerlocations:
    aliases:
      - plocations
      - playerlocs
      - pls
  country:
    aliases:
      - playerlocations-country
      - player-country
